apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: argocdworkspace
images:
- name: argocdapp
  newName: srsantosdev/argocd-example
  newTag: c56469328bcab45b0addbc8d77afa5219b78cd40
